import React, { Component, Fragment } from 'react';
import PropTypes from 'prop-types';
import AppBar from '@material-ui/core/AppBar';
import CssBaseline from '@material-ui/core/CssBaseline';
import Typography from '@material-ui/core/Typography';
import IconButton from '@material-ui/core/IconButton';
import Button from '@material-ui/core/Button';
import SearchIcon from '@material-ui/icons/Search';
import { Grid } from '@material-ui/core';

const styles = theme => ({
    text: {
        paddingTop: theme.spacing.unit * 2,
        paddingLeft: theme.spacing.unit * 2,
        paddingRight: theme.spacing.unit * 2,
    },
    paper: {
        paddingBottom: 50,
    },
    list: {
        marginBottom: theme.spacing.unit * 2,
    },
    subHeader: {
        backgroundColor: theme.palette.background.paper,
    },
    appBar: {
        top: 'auto',
        bottom: 0,
    },
    toolbar: {
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    fabButton: {
        position: 'absolute',
        top: -30,
        left: 0,
        right: 0,
        margin: '0 auto',
    },
});

const messages = [
    {
        id: 1,
        primary: 'Brunch this week?',
        secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
        person: '/static/images/adeel.jpg',
    },
    {
        id: 2,
        primary: 'Birthday Gift',
        secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
        person: '/static/images/uxceo-128.jpg',
    },
    {
        id: 3,
        primary: 'Recipe to try',
        secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
        person: '/static/images/remy.jpg',
    },
    {
        id: 4,
        primary: 'Yes!',
        secondary: 'I have the tickets to the ReactConf for this year.',
        person: '/static/images/uxceo-128.jpg',
    },
    {
        id: 5,
        primary: "Doctor's Appointment",
        secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
        person: '/static/images/adeel.jpg',
    },
    {
        id: 6,
        primary: 'Discussion',
        secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
        person: '/static/images/remy.jpg',
    },
    {
        id: 7,
        primary: 'Summer BBQ',
        secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
        person: '/static/images/uxceo-128.jpg',
    },
];


class FooterPage extends Component {
    render() {
        return (
            <React.Fragment>
                <CssBaseline />
                <AppBar position="sticky" color="primary" className={styles.appBar}>
                    <Grid container spacing={16} justify="center">
                        <Grid item xs={12} sm={6} md={3} alignItems="center">
                       
                          
                        </Grid>
                        <Grid item xs={12} sm={6} md={3}>
                            <Typography>Test</Typography>
                        </Grid>
                        <Grid item xs={12} sm={6} md={3}>
                            <Button variant="raised" color="secondary" aria-label="Add" >
                                Contact Us
                            </Button>
                            <IconButton color="inherit">
                                <SearchIcon />
                            </IconButton>
                        </Grid>
                    </Grid>
                </AppBar>
            </React.Fragment>
        );
    }
}

FooterPage.propTypes = {
    classes: PropTypes.object.isRequired,
};

export default FooterPage;